import { generateSchemas, detectDrift, getChangedFiles, run } from './sync-schema'

const SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL

function createBranch(): string {
  const date = new Date().toISOString().split('T')[0]
  const branch = `schema-sync/${date}`
  run('git config user.email "github-actions[bot]@users.noreply.github.com"')
  run('git config user.name "github-actions[bot]"')
  run(`git checkout -b ${branch}`)
  return branch
}

function commitAndPush(branch: string): void {
  run('git add framework/api/schema/')
  run('git commit -m "chore: sync schema from swagger"')
  run(`git push origin ${branch}`)
}

function createPullRequest(branch: string, changedFiles: string[]): string {
  const fileList = changedFiles.map((f) => `- ${f}`).join('\n')
  const body = [
    '## Schema drift detected',
    '',
    'The following schema files have drifted from the live Swagger spec:',
    '',
    fileList,
    '',
    '_Auto-generated by schema-sync workflow._',
  ].join('\n')

  return run(
    `gh pr create --title "chore: schema sync $(date +%Y-%m-%d)" --body "${body.replace(/"/g, '\\"')}" --base main --head ${branch}`,
  )
}

async function notifySlack(prUrl: string, changedFiles: string[]): Promise<void> {
  if (!SLACK_WEBHOOK_URL) return

  const payload = {
    text: '*Schema drift detected*',
    blocks: [
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Schema drift detected* — ${changedFiles.length} file(s) changed.\n<${prUrl}|View PR>`,
        },
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: changedFiles.map((f) => `• \`${f}\``).join('\n'),
        },
      },
    ],
  }

  const response = await fetch(SLACK_WEBHOOK_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  })

  if (!response.ok) {
    console.warn(`Slack notification failed: ${response.status} ${response.statusText}`)
  }
}

async function main(): Promise<void> {
  generateSchemas()

  const drift = detectDrift()
  if (!drift) {
    console.log('No schema drift detected. Nothing to do.')
    return
  }

  const changedFiles = getChangedFiles()
  console.log(`Drift detected in ${changedFiles.length} file(s):`, changedFiles)

  const branch = createBranch()
  commitAndPush(branch)

  const prUrl = createPullRequest(branch, changedFiles)
  console.log(`PR created: ${prUrl}`)

  await notifySlack(prUrl, changedFiles)
  console.log('Slack notification sent.')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
