/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * InvoiceLab API
 * REST API for managing clients, invoices, and line items
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * @summary List all clients
 */
export const GetClientsResponseItem = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "email": zod.string().email().optional(),
  "phone": zod.string().nullish(),
  "address": zod.string().nullish(),
  "created_at": zod.string().datetime({"offset":true}).optional()
})
export const GetClientsResponse = zod.array(GetClientsResponseItem)

/**
 * @summary Create a client
 */



export const PostClientsBody = zod.object({
  "name": zod.string().min(1),
  "email": zod.string().email(),
  "phone": zod.string().optional(),
  "address": zod.string().optional()
})

export const PostClientsResponse = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "email": zod.string().email().optional(),
  "phone": zod.string().nullish(),
  "address": zod.string().nullish(),
  "created_at": zod.string().datetime({"offset":true}).optional()
})

/**
 * @summary Get a client by ID
 */
export const GetClientsIdParams = zod.object({
  "id": zod.number()
})

export const GetClientsIdResponse = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "email": zod.string().email().optional(),
  "phone": zod.string().nullish(),
  "address": zod.string().nullish(),
  "created_at": zod.string().datetime({"offset":true}).optional()
})

/**
 * @summary Update a client (partial — any subset of fields)
 */
export const PutClientsIdParams = zod.object({
  "id": zod.number()
})




export const PutClientsIdBody = zod.object({
  "name": zod.string().min(1),
  "email": zod.string().email(),
  "phone": zod.string().optional(),
  "address": zod.string().optional()
})

export const PutClientsIdResponse = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "email": zod.string().email().optional(),
  "phone": zod.string().nullish(),
  "address": zod.string().nullish(),
  "created_at": zod.string().datetime({"offset":true}).optional()
})

/**
 * @summary Delete a client
 */
export const DeleteClientsIdParams = zod.object({
  "id": zod.number()
})

export const DeleteClientsIdResponse = zod.void()

/**
 * Returns invoices belonging to the given client, ordered by creation date descending, each including subtotal.
 * @summary List all invoices for a client
 */
export const GetClientsIdInvoicesParams = zod.object({
  "id": zod.number()
})

export const GetClientsIdInvoicesQueryParams = zod.object({
  "status": zod.enum(['draft', 'sent', 'paid']).optional().describe('Filter by invoice status')
})

export const getClientsIdInvoicesResponseCurrencyMin = 3;
export const getClientsIdInvoicesResponseCurrencyMax = 3;

export const getClientsIdInvoicesResponseTaxRateMin = 0;
export const getClientsIdInvoicesResponseTaxRateMax = 100;



export const GetClientsIdInvoicesResponseItem = zod.object({
  "id": zod.number().optional(),
  "client_id": zod.number().optional(),
  "client_name": zod.string().optional(),
  "status": zod.enum(['draft', 'sent', 'paid']).optional(),
  "currency": zod.string().min(getClientsIdInvoicesResponseCurrencyMin).max(getClientsIdInvoicesResponseCurrencyMax).optional().describe('ISO 4217 currency code'),
  "issue_date": zod.string().date().optional(),
  "due_date": zod.string().date().optional(),
  "tax_rate": zod.number().min(getClientsIdInvoicesResponseTaxRateMin).max(getClientsIdInvoicesResponseTaxRateMax).optional(),
  "memo": zod.string().nullish(),
  "subtotal": zod.number().optional(),
  "created_at": zod.string().datetime({"offset":true}).optional(),
  "updated_at": zod.string().datetime({"offset":true}).optional()
})
export const GetClientsIdInvoicesResponse = zod.array(GetClientsIdInvoicesResponseItem)

// Inferred TypeScript types
export type GetClientsResponseItem = zod.infer<typeof GetClientsResponseItem>
export type GetClientsResponse = zod.infer<typeof GetClientsResponse>
export type PostClientsBody = zod.infer<typeof PostClientsBody>
export type PostClientsResponse = zod.infer<typeof PostClientsResponse>
export type GetClientsIdParams = zod.infer<typeof GetClientsIdParams>
export type GetClientsIdResponse = zod.infer<typeof GetClientsIdResponse>
export type PutClientsIdParams = zod.infer<typeof PutClientsIdParams>
export type PutClientsIdBody = zod.infer<typeof PutClientsIdBody>
export type PutClientsIdResponse = zod.infer<typeof PutClientsIdResponse>
export type DeleteClientsIdParams = zod.infer<typeof DeleteClientsIdParams>
export type DeleteClientsIdResponse = zod.infer<typeof DeleteClientsIdResponse>
export type GetClientsIdInvoicesParams = zod.infer<typeof GetClientsIdInvoicesParams>
export type GetClientsIdInvoicesQueryParams = zod.infer<typeof GetClientsIdInvoicesQueryParams>
export type GetClientsIdInvoicesResponseItem = zod.infer<typeof GetClientsIdInvoicesResponseItem>
export type GetClientsIdInvoicesResponse = zod.infer<typeof GetClientsIdInvoicesResponse>
