/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * InvoiceLab API
 * REST API for managing clients, invoices, and line items
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * @summary List all clients
 */
export const GetClientsResponseItem = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "email": zod.string().email().optional(),
  "phone": zod.string().nullish(),
  "address": zod.string().nullish(),
  "created_at": zod.string().datetime({"offset":true}).optional()
})
export const GetClientsResponse = zod.array(GetClientsResponseItem)

/**
 * @summary Create a client
 */



export const PostClientsBody = zod.object({
  "name": zod.string().min(1),
  "email": zod.string().email(),
  "phone": zod.string().optional(),
  "address": zod.string().optional()
})

export const PostClientsResponse = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "email": zod.string().email().optional(),
  "phone": zod.string().nullish(),
  "address": zod.string().nullish(),
  "created_at": zod.string().datetime({"offset":true}).optional()
})

/**
 * @summary Get a client by ID
 */
export const GetClientsIdParams = zod.object({
  "id": zod.number()
})

export const GetClientsIdResponse = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "email": zod.string().email().optional(),
  "phone": zod.string().nullish(),
  "address": zod.string().nullish(),
  "created_at": zod.string().datetime({"offset":true}).optional()
})

/**
 * @summary Update a client (partial — any subset of fields)
 */
export const PutClientsIdParams = zod.object({
  "id": zod.number()
})




export const PutClientsIdBody = zod.object({
  "name": zod.string().min(1),
  "email": zod.string().email(),
  "phone": zod.string().optional(),
  "address": zod.string().optional()
})

export const PutClientsIdResponse = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "email": zod.string().email().optional(),
  "phone": zod.string().nullish(),
  "address": zod.string().nullish(),
  "created_at": zod.string().datetime({"offset":true}).optional()
})

/**
 * @summary Delete a client
 */
export const DeleteClientsIdParams = zod.object({
  "id": zod.number()
})

export const DeleteClientsIdResponse = zod.void()

// Inferred TypeScript types
export type GetClientsResponseItem = zod.infer<typeof GetClientsResponseItem>
export type GetClientsResponse = zod.infer<typeof GetClientsResponse>
export type PostClientsBody = zod.infer<typeof PostClientsBody>
export type PostClientsResponse = zod.infer<typeof PostClientsResponse>
export type GetClientsIdParams = zod.infer<typeof GetClientsIdParams>
export type GetClientsIdResponse = zod.infer<typeof GetClientsIdResponse>
export type PutClientsIdParams = zod.infer<typeof PutClientsIdParams>
export type PutClientsIdBody = zod.infer<typeof PutClientsIdBody>
export type PutClientsIdResponse = zod.infer<typeof PutClientsIdResponse>
export type DeleteClientsIdParams = zod.infer<typeof DeleteClientsIdParams>
export type DeleteClientsIdResponse = zod.infer<typeof DeleteClientsIdResponse>
