/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * InvoiceLab API
 * REST API for managing clients, invoices, and line items
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * @summary Health check
 */
export const GetHealthResponse = zod.object({
  "status": zod.string().optional()
})

// Inferred TypeScript types
export type GetHealthResponse = zod.infer<typeof GetHealthResponse>
