/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * InvoiceLab API
 * REST API for managing clients, invoices, and line items
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * @summary List all invoices
 */
export const GetInvoicesResponseItem = zod.object({
  "id": zod.number().optional(),
  "client_id": zod.number().optional(),
  "client_name": zod.string().optional(),
  "status": zod.enum(['draft', 'sent', 'paid']).optional(),
  "issue_date": zod.string().date().optional(),
  "due_date": zod.string().date().optional(),
  "tax_rate": zod.number().optional(),
  "notes": zod.string().nullish(),
  "subtotal": zod.number().optional(),
  "created_at": zod.string().datetime({"offset":true}).optional(),
  "updated_at": zod.string().datetime({"offset":true}).optional()
})
export const GetInvoicesResponse = zod.array(GetInvoicesResponseItem)

/**
 * Creates invoice and all line items in a single transaction. Status starts as `draft`.
 * @summary Create an invoice with line items
 */
export const postInvoicesBodyTaxRateDefault = 0;
export const postInvoicesBodyTaxRateMin = 0;
export const postInvoicesBodyTaxRateMax = 100;


export const postInvoicesBodyLineItemsItemQuantityExclusiveMin = 0;

export const postInvoicesBodyLineItemsItemUnitPriceMin = 0;




export const PostInvoicesBody = zod.object({
  "client_id": zod.number(),
  "issue_date": zod.string().date(),
  "due_date": zod.string().date(),
  "tax_rate": zod.number().min(postInvoicesBodyTaxRateMin).max(postInvoicesBodyTaxRateMax).default(postInvoicesBodyTaxRateDefault),
  "notes": zod.string().optional(),
  "line_items": zod.array(zod.object({
  "description": zod.string().min(1),
  "quantity": zod.number().gt(postInvoicesBodyLineItemsItemQuantityExclusiveMin),
  "unit_price": zod.number().min(postInvoicesBodyLineItemsItemUnitPriceMin)
})).min(1)
})

export const PostInvoicesResponse = zod.object({
  "id": zod.number().optional(),
  "client_id": zod.number().optional(),
  "client_name": zod.string().optional(),
  "status": zod.enum(['draft', 'sent', 'paid']).optional(),
  "issue_date": zod.string().date().optional(),
  "due_date": zod.string().date().optional(),
  "tax_rate": zod.number().optional(),
  "notes": zod.string().nullish(),
  "subtotal": zod.number().optional(),
  "created_at": zod.string().datetime({"offset":true}).optional(),
  "updated_at": zod.string().datetime({"offset":true}).optional()
})

/**
 * @summary Get invoice by ID with line items
 */
export const GetInvoicesIdParams = zod.object({
  "id": zod.number()
})

export const GetInvoicesIdResponse = zod.object({
  "id": zod.number().optional(),
  "client_id": zod.number().optional(),
  "client_name": zod.string().optional(),
  "status": zod.enum(['draft', 'sent', 'paid']).optional(),
  "issue_date": zod.string().date().optional(),
  "due_date": zod.string().date().optional(),
  "tax_rate": zod.number().optional(),
  "notes": zod.string().nullish(),
  "subtotal": zod.number().optional(),
  "created_at": zod.string().datetime({"offset":true}).optional(),
  "updated_at": zod.string().datetime({"offset":true}).optional()
}).and(zod.object({
  "line_items": zod.array(zod.object({
  "id": zod.number().optional(),
  "invoice_id": zod.number().optional(),
  "description": zod.string().optional(),
  "quantity": zod.number().optional(),
  "unit_price": zod.number().optional()
})).optional()
}))

/**
 * Replaces all fields and deletes + re-inserts all line items in a transaction. Only allowed while status is `draft`.
 * @summary Replace invoice and line items (draft only)
 */
export const PutInvoicesIdParams = zod.object({
  "id": zod.number()
})

export const putInvoicesIdBodyTaxRateDefault = 0;
export const putInvoicesIdBodyTaxRateMin = 0;
export const putInvoicesIdBodyTaxRateMax = 100;


export const putInvoicesIdBodyLineItemsItemQuantityExclusiveMin = 0;

export const putInvoicesIdBodyLineItemsItemUnitPriceMin = 0;




export const PutInvoicesIdBody = zod.object({
  "client_id": zod.number(),
  "issue_date": zod.string().date(),
  "due_date": zod.string().date(),
  "tax_rate": zod.number().min(putInvoicesIdBodyTaxRateMin).max(putInvoicesIdBodyTaxRateMax).default(putInvoicesIdBodyTaxRateDefault),
  "notes": zod.string().optional(),
  "line_items": zod.array(zod.object({
  "description": zod.string().min(1),
  "quantity": zod.number().gt(putInvoicesIdBodyLineItemsItemQuantityExclusiveMin),
  "unit_price": zod.number().min(putInvoicesIdBodyLineItemsItemUnitPriceMin)
})).min(1)
})

export const PutInvoicesIdResponse = zod.object({
  "id": zod.number().optional(),
  "client_id": zod.number().optional(),
  "client_name": zod.string().optional(),
  "status": zod.enum(['draft', 'sent', 'paid']).optional(),
  "issue_date": zod.string().date().optional(),
  "due_date": zod.string().date().optional(),
  "tax_rate": zod.number().optional(),
  "notes": zod.string().nullish(),
  "subtotal": zod.number().optional(),
  "created_at": zod.string().datetime({"offset":true}).optional(),
  "updated_at": zod.string().datetime({"offset":true}).optional()
})

/**
 * Deletes the invoice and cascades to line_items. Only allowed while status is `draft`.
 * @summary Delete an invoice (draft only)
 */
export const DeleteInvoicesIdParams = zod.object({
  "id": zod.number()
})

export const DeleteInvoicesIdResponse = zod.void()

/**
 * @summary Get computed totals for an invoice
 */
export const GetInvoicesIdSummaryParams = zod.object({
  "id": zod.number()
})

export const GetInvoicesIdSummaryResponse = zod.object({
  "subtotal": zod.number().optional(),
  "tax_rate": zod.number().optional(),
  "tax_amount": zod.number().optional(),
  "total": zod.number().optional()
})

/**
 * Allowed transitions: draft → sent → paid. Reverse transitions are rejected.
 * @summary Transition invoice status
 */
export const PatchInvoicesIdStatusParams = zod.object({
  "id": zod.number()
})

export const PatchInvoicesIdStatusBody = zod.object({
  "status": zod.enum(['draft', 'sent', 'paid'])
})

export const PatchInvoicesIdStatusResponse = zod.object({
  "id": zod.number().optional(),
  "client_id": zod.number().optional(),
  "client_name": zod.string().optional(),
  "status": zod.enum(['draft', 'sent', 'paid']).optional(),
  "issue_date": zod.string().date().optional(),
  "due_date": zod.string().date().optional(),
  "tax_rate": zod.number().optional(),
  "notes": zod.string().nullish(),
  "subtotal": zod.number().optional(),
  "created_at": zod.string().datetime({"offset":true}).optional(),
  "updated_at": zod.string().datetime({"offset":true}).optional()
})

// Inferred TypeScript types
export type GetInvoicesResponseItem = zod.infer<typeof GetInvoicesResponseItem>
export type GetInvoicesResponse = zod.infer<typeof GetInvoicesResponse>
export type PostInvoicesBody = zod.infer<typeof PostInvoicesBody>
export type PostInvoicesResponse = zod.infer<typeof PostInvoicesResponse>
export type GetInvoicesIdParams = zod.infer<typeof GetInvoicesIdParams>
export type GetInvoicesIdResponse = zod.infer<typeof GetInvoicesIdResponse>
export type PutInvoicesIdParams = zod.infer<typeof PutInvoicesIdParams>
export type PutInvoicesIdBody = zod.infer<typeof PutInvoicesIdBody>
export type PutInvoicesIdResponse = zod.infer<typeof PutInvoicesIdResponse>
export type DeleteInvoicesIdParams = zod.infer<typeof DeleteInvoicesIdParams>
export type DeleteInvoicesIdResponse = zod.infer<typeof DeleteInvoicesIdResponse>
export type GetInvoicesIdSummaryParams = zod.infer<typeof GetInvoicesIdSummaryParams>
export type GetInvoicesIdSummaryResponse = zod.infer<typeof GetInvoicesIdSummaryResponse>
export type PatchInvoicesIdStatusParams = zod.infer<typeof PatchInvoicesIdStatusParams>
export type PatchInvoicesIdStatusBody = zod.infer<typeof PatchInvoicesIdStatusBody>
export type PatchInvoicesIdStatusResponse = zod.infer<typeof PatchInvoicesIdStatusResponse>
